### ISSUE TITLE
Logo appears blurry

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#1]
<img width="187" alt="screen shot 2016-01-25 at 12 27 15 am" src="https://cloud.githubusercontent.com/assets/16873520/12543157/6ebd514c-c2fa-11e5-921c-55291ea8d30e.png">

Need to make sure that all assets we use are saved out @2x, to be retina display friendly

**Comment by nisho5** [comment]
- Included Retina display feature, wherever it applies it replace a higher res version of a pic.

**Comment by laurakberglund** [comment]
Is this retina display feature already enabled? The logos are still looking blurry to me. (I am on a retina screen)

**Comment by nisho5** [comment]
Please check now

**Comment by laurakberglund** [comment]
Looks fantastic now! :)
