### ISSUE TITLE
Hover state for main button style

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#10]
<img width="326" alt="screen shot 2016-01-25 at 1 29 28 am" src="https://cloud.githubusercontent.com/assets/16873520/12543964/200f6b62-c303-11e5-9584-ff7a4be06157.png">

On homepage:

The text for the button style on hover should be the color of the background beneath it. So in this case, it should be the light yellow color, not white

**Comment by nisho5** [comment]
- Done (also in "how we give back", "meet the chef" and "group orders" pages)

**Comment by nisho5** [comment]
Please check

**Comment by laurakberglund** [comment]
Looks good, thank you!
