### ISSUE TITLE
Order food page: days with multiple food options should be full-width

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#11]
<img width="1440" alt="screen shot 2016-01-25 at 1 32 27 am" src="https://cloud.githubusercontent.com/assets/16873520/12544017/b5a30648-c303-11e5-8539-13322f43ca50.png">
<img width="823" alt="screen shot 2016-01-25 at 1 32 52 am" src="https://cloud.githubusercontent.com/assets/16873520/12544018/b5af28e2-c303-11e5-8f3a-2f65fed1f580.png">

I remember you noting in your email that we needed to come up with a way to feature the food available at least 48 hours in advance. This way of ordering is already built into the design on this page - it's the days that have multiple food options in one "block". This block is actually a clickable slideshow, that will take you through each food option available that day. This module should be full- width, touching the edges of the browser window always.

The green overlay with the check mark in a circle is actually the click state when a user decides on a box for that day, and clicks on that square within that day's offerings.

Let me know if this needs further clarification. It's hard to talk through in writing!

**Comment by nisho5** [comment]
- I added the clickable feature and the transparent overlap.
- Once we have some realistic data I will continue this feature depending on the content

**Comment by laurakberglund** [comment]
Ok, we can put this on hold for now, thank you!

**Comment by laurakberglund** [comment]
When will days with multiple options be added? That's an important part to be able to QA!

**Comment by nisho5** [comment]
I had added this, but @kimmyzouki wants to hide this feature for initial launch.

**Comment by laurakberglund** [comment]
ok, then I will close this issue for now, thanks!
