### ISSUE TITLE
Individual Orders page: logo gets bigger on sticky nav

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#12]
<img width="598" alt="screen shot 2016-02-01 at 3 11 13 am" src="https://cloud.githubusercontent.com/assets/16873520/12711905/a25477dc-c891-11e5-88ea-7ff73063cd4b.png">
<img width="587" alt="screen shot 2016-02-01 at 3 12 43 am" src="https://cloud.githubusercontent.com/assets/16873520/12711911/af9582b0-c891-11e5-9c78-d6fa4f638689.png">

On the Individual orders page, once the green sticky nav pops up, the Good Bytes logo gets much bigger. It should actually shrink in size when it is in the sticky nav, not get bigger. 

Then, once you scroll back up to the top and the green sticky nav disappears, the logo stays the bigger size, which should not happen.

**Comment by nisho5** [comment]
Also, Please check again in the new address I will send you later tonight.

**Comment by laurakberglund** [comment]
It is still getting bigger to me. I am currently looking in Chrome if that helps at all.
