### ISSUE TITLE
Body Copy style throughout site

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#13]
<img width="317" alt="screen shot 2016-02-01 at 3 25 51 am" src="https://cloud.githubusercontent.com/assets/16873520/12712081/88220152-c893-11e5-9b69-1878798055a6.png">

<img width="272" alt="screen shot 2016-02-01 at 3 27 20 am" src="https://cloud.githubusercontent.com/assets/16873520/12712109/bf4ea748-c893-11e5-888c-fa33690d3e92.png">

For all the body copy on the site, we need to increase the tracking slightly and also increase the leading slightly. It feels tight for all body copy on the site.

**Comment by nisho5** [comment]
Please check

**Comment by laurakberglund** [comment]
Looks very nice!
