### ISSUE TITLE
Individual orders page: change text

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#14]
This headline should just say "ORDER NOW" in black.

<img width="1228" alt="screen shot 2016-02-01 at 3 28 57 am" src="https://cloud.githubusercontent.com/assets/16873520/12712141/08d13a5c-c894-11e5-8491-c5084d254846.png">

**Comment by nisho5** [comment]
I'm sorry, I didn't get what you mean. What headline ?

**Comment by laurakberglund** [comment]
The headline "FOOD THAT MAKES YOU FEEL SOCIAL GOOD." doesn't make sense, and is too long to fit here comfortably. We also need to make it very obviously the ordering page, so this text should just say "ORDER NOW" instead.

I'm assigning Kimmy to this just so he can see this change.

**Comment by nisho5** [comment]
Done

**Comment by kimmyzouki** [comment]
Yes sure all of this headline does not make sense.
Will adjust this!
