### ISSUE TITLE
Sticky nav text

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#15]
<img width="259" alt="screen shot 2016-02-01 at 3 30 10 am" src="https://cloud.githubusercontent.com/assets/16873520/12712152/2d4a0788-c894-11e5-8e78-11ff998bf82c.png">
<img width="605" alt="screen shot 2016-02-01 at 3 31 00 am" src="https://cloud.githubusercontent.com/assets/16873520/12712158/3d4daa54-c894-11e5-8930-88238ad66256.png">

Text in sticky nav should be centered vertically within green band.

It should also be more tracked out.

**Comment by nisho5** [comment]
Please check

**Comment by laurakberglund** [comment]
<img width="615" alt="screen shot 2016-02-03 at 12 42 43 am" src="https://cloud.githubusercontent.com/assets/16873520/12774018/10d9f5f0-ca0f-11e5-9a42-d086f8d92501.png">

It is still not looking centered vertically within the green band

**Comment by laurakberglund** [comment]
<img width="805" alt="screen shot 2016-03-03 at 1 01 07 am" src="https://cloud.githubusercontent.com/assets/16873520/13486024/7262303e-e0db-11e5-9844-b9b374ae20b1.png">

Still some strange stuff happening with the logo size changing randomly, and the nav text jumping up inside the green bar. (It should always be vertically centered)
