### ISSUE TITLE
Meet the chef page: vertically center header text

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#16]
<img width="610" alt="screen shot 2016-02-01 at 3 32 46 am" src="https://cloud.githubusercontent.com/assets/16873520/12712179/88eb617c-c894-11e5-801d-27f38f5f9181.png">

Can you move up this "Meet the chef" text a bit within this pink band, so it feels more vertically centered within it?

**Comment by nisho5** [comment]
Please check, same for "how we give back"

**Comment by laurakberglund** [comment]
looks better!
