### ISSUE TITLE
How we are giving back page: "partnership for innovation" section

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#17]
<img width="849" alt="screen shot 2016-02-01 at 3 34 55 am" src="https://cloud.githubusercontent.com/assets/16873520/12712227/e7dd3714-c894-11e5-8c01-121e4e9593c8.png">
<img width="598" alt="screen shot 2016-02-01 at 3 36 01 am" src="https://cloud.githubusercontent.com/assets/16873520/12712231/edca347e-c894-11e5-99fb-dd4140a7e122.png">

This section appears tight - can we add more space vertically between all the elements in this section?

Also, the Good Bytes logo appears a touch blurry compared to the donors choose one. Can it become more crisp?

Lastly, the donors choose logo should not be a link on this page. This should just be a static image for both logos here.

**Comment by nisho5** [comment]
Please check

**Comment by laurakberglund** [comment]
Looks good, now we just need to make sure the logo block is centered under the "Partnership for Innovation" text:

<img width="802" alt="screen shot 2016-02-03 at 12 41 32 am" src="https://cloud.githubusercontent.com/assets/16873520/12773993/e4add6cc-ca0e-11e5-88a8-8efa7e4d3c91.png">

**Comment by nisho5** [comment]
I believe it is. no? how much do u think it should be moved?

**Comment by laurakberglund** [comment]
The block of the Good Bytes logo, the small grey line, and the Donors Choose logo as a single unit should appear centered under the "A partnership for innovation" text. Right now it is too far to the right.

**Comment by nisho5** [comment]
Done... the thing is the 2 logos are not equal.
I believe it still looks weird now.
Can we somehow make the logos visually equal width?

**Comment by laurakberglund** [comment]
Yea, it looks strange now because you also moved the header type ("Partnership for innovation"). All that needed to move was the logo lockup. 

I've created a quick animation to visualize how to make it look correct from where it is now on the site:
![partnership-for-innovation-edit](https://cloud.githubusercontent.com/assets/16873520/13561485/7ad42470-e3fb-11e5-995b-d3685f0c4617.gif)

The point is to make everything look perfectly centered on the page, and the logo lockup should be centered as one unit, not as two separate logos.

**Comment by nisho5** [comment]
Ok, I think i got it this time

**Comment by nisho5** [comment]
Ok, I think i got it this time

**Comment by laurakberglund** [comment]
yes, fantastic!
