### ISSUE TITLE
Individual orders page: image itself should be a link to order

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#18]
<img width="1029" alt="screen shot 2016-02-01 at 3 39 16 am" src="https://cloud.githubusercontent.com/assets/16873520/12712305/720e367c-c895-11e5-81e1-6299bbfd6a82.png">

Right now, just the "order now" button opens up the product details modal, but you should be able to click the photo, the name, and the green band as well and have them all link to the product details modal.

**Comment by nisho5** [comment]
Fixed this for now.
But still I can only finalize this once i have the full feature ready.

**Comment by laurakberglund** [comment]
Ok, good to know. I will close this for now then!
