### ISSUE TITLE
Individual orders page: product details modal

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#19]
This popup modal feels very tight. Please match the design of this more closely to what I have in the .ai file. Currently, I'm not able to open up the modal (maybe you are working on it now!), but you can see the original design here, and how everything has more breathing room:

<img width="795" alt="screen shot 2016-02-01 at 3 42 54 am" src="https://cloud.githubusercontent.com/assets/16873520/12712375/e8825770-c895-11e5-9e7b-0bf8a7d9dc78.png">

**Comment by nisho5** [comment]
Please check

**Comment by laurakberglund** [comment]
It's looking better! I have some specific changes now that will help get it all the way there:
<img width="868" alt="screen shot 2016-02-03 at 12 35 01 am" src="https://cloud.githubusercontent.com/assets/16873520/12773903/13b29c2e-ca0e-11e5-995d-6f9ef0dd16bc.png">
- remove drop shadow from the modal altogether
- type style in the green band at the top needs to be more tracked out, less leading, a bit smaller in size to match the size of the nav text, and be semi-bold (if it's not already, hard to tell)
- missing "X" at top right to click out of the modal
- A few spacing issues where elements are too close to one another (see my notes in the screenshot)
- Make the width of the whole modal box the same with as the menu item boxes behind it on the Individual Orders page.

**Comment by nisho5** [comment]
I believe i got all points covered. Please check
