### ISSUE TITLE
Order of nav

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#20]
Hey Kimmy,

When I look at the site as if I were a new user, I'm having a really hard time understanding that I can order food online right then and there. Calling the online ordering part of the website "Individual Orders" is a confusing name to the average Brooklyn tech employee. I think we need to give this tab a more actionable name, so people know exactly where they are going when they click it. Can we just call it "Order Online"? (It is actually the only place you can order online, since the Group Orders page is purely informational.)

Also, I would re-organize the order of the items in the nav, because people usually look to the top right of a browser window for more actionable items, like "Order Now".

Can we make the order like this:
How We Give Back, The Chef, [LOGO], Group Orders, Order Now, [SOCIAL ICONS]?

<img width="1307" alt="screen shot 2016-02-03 at 12 09 08 am" src="https://cloud.githubusercontent.com/assets/16873520/12773594/220cd332-ca0b-11e5-8a0a-0c48a9232a69.png">

**Comment by nisho5** [comment]
@kimmyzouki  please advise

**Comment by kimmyzouki** [comment]
For some reason i just saw this and yes you make whatever you think is
better take all the calls you need to take!
