### ISSUE TITLE
Individual Orders page: nav needs to change

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#21]
In my .ai file, you can see how the Individual orders page features a new nav. We need to make sure that once you are in the live Online Ordering section of the site, you have the proper Online Ordering nav:

(Account, About, [LOGO], Bag, Help)
<img width="1018" alt="screen shot 2016-02-03 at 12 18 35 am" src="https://cloud.githubusercontent.com/assets/16873520/12773660/b484b7ca-ca0b-11e5-8617-6fbb915da478.png">

This is what is in there now:
<img width="1307" alt="screen shot 2016-02-03 at 12 16 10 am" src="https://cloud.githubusercontent.com/assets/16873520/12773662/b771338c-ca0b-11e5-9480-f404a5fcb0c3.png">

**Comment by nisho5** [comment]
Done
