### ISSUE TITLE
Spacing between footer items

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#22]
(to do at the end)

**Comment by laurakberglund** [comment]
The spacing between the footer items should be an equal distance between each one, but it should be less space. Also, the text size should get smaller in the footer, and the tracking between the letters should increase. See the difference between what we have on the site now, and the design in the .ai file:

<img width="1235" alt="screen shot 2016-03-07 at 12 16 48 am" src="https://cloud.githubusercontent.com/assets/16873520/13561339/f0a12a7e-e3f9-11e5-897f-59f7fad67882.png">

**Comment by laurakberglund** [comment]
size of type in footer should be 10px. It's 12px now.

**Comment by nisho5** [comment]
please check
