### ISSUE TITLE
Illustrations ready for "How We Give Back" page

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#23]
http://goodbytesbox.com/web15/howwegiveback.html

Please upload each PNG at 100% size, to look like this:
<img width="975" alt="screen shot 2016-02-17 at 1 45 21 am" src="https://cloud.githubusercontent.com/assets/16873520/13101909/37187976-d518-11e5-99d3-86b1f1303d2c.png">

![illo_howwegivebackpage_1](https://cloud.githubusercontent.com/assets/16873520/13101921/48b733ac-d518-11e5-8184-9433fa035ae9.png)
![illo_howwegivebackpage_2](https://cloud.githubusercontent.com/assets/16873520/13101922/48b7a3a0-d518-11e5-9d52-052e8181ea3f.png)
![illo_howwegivebackpage_3](https://cloud.githubusercontent.com/assets/16873520/13101923/48bbf982-d518-11e5-85ad-a9378bc3e5f1.png)

**Comment by nisho5** [comment]
Thank you
