### ISSUE TITLE
Illustrations ready to upload for homepage

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#24]
http://goodbytesbox.com/web15/index.html

Full-width illustrations should look like this (use at 100%):
<img width="978" alt="screen shot 2016-02-17 at 1 49 51 am" src="https://cloud.githubusercontent.com/assets/16873520/13102133/b1ca9478-d519-11e5-99cd-84f49d0b13ac.png">

Half-width illustrations should look like this (use at 100%):
<img width="977" alt="screen shot 2016-02-17 at 1 52 50 am" src="https://cloud.githubusercontent.com/assets/16873520/13102142/bc1b1376-d519-11e5-956d-64791ef2eb85.png">

![illo_48hoursinadvance](https://cloud.githubusercontent.com/assets/16873520/13102153/ca3d5acc-d519-11e5-8478-c30d7c56cbfd.png)
![illo_childinclassroom](https://cloud.githubusercontent.com/assets/16873520/13102154/ca43c434-d519-11e5-8fa4-950b4a380c49.png)
![illo_deliverytoyourdesk](https://cloud.githubusercontent.com/assets/16873520/13102155/ca469e52-d519-11e5-95ef-e1e37601b8f1.png)
![illo_grouporders](https://cloud.githubusercontent.com/assets/16873520/13102156/ca468d90-d519-11e5-93e6-d528c72999f0.png)
![illo_orderby10am](https://cloud.githubusercontent.com/assets/16873520/13102157/ca46c9cc-d519-11e5-835c-5a53bdb185c8.png)

**Comment by nisho5** [comment]
Thank you
