### ISSUE TITLE
"Cheers to that" text written twice

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#26]
<img width="485" alt="screen shot 2016-03-03 at 1 02 43 am" src="https://cloud.githubusercontent.com/assets/16873520/13486054/b062cac4-e0db-11e5-9b17-5a64b412d56a.png">

 on the "Order now" page, it says "Cheers to that" twice. It should say it once, but all be on one line, and the same text size as the copy in the dek before it.

**Comment by nisho5** [comment]
Fixed

**Comment by laurakberglund** [comment]
Please style the "Cheers to that" text in the same format as the body text above it. (It should not be smaller or all caps)

<img width="616" alt="screen shot 2016-03-07 at 12 06 50 am" src="https://cloud.githubusercontent.com/assets/16873520/13561237/97eaaf14-e3f8-11e5-8811-9435496f56a8.png">

**Comment by nisho5** [comment]
Done

**Comment by laurakberglund** [comment]
Looks good! But now the width of this container has gotten a lot narrower - can we make the width what it used to be? (Want to make sure the headline in this section can remain on one line in desktop browser size) Thank you!

<img width="702" alt="screen shot 2016-03-08 at 10 41 43 pm" src="https://cloud.githubusercontent.com/assets/16873520/13624770/12a91484-e57f-11e5-91e1-a94d5516fa1d.png">
