### ISSUE TITLE
Tabbouleh & falafel box item not formatted correctly

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#27]
<img width="1167" alt="screen shot 2016-03-03 at 1 04 15 am" src="https://cloud.githubusercontent.com/assets/16873520/13486088/efe51576-e0db-11e5-8a8a-be952c127cc2.png">

This image is not in the same format as the others, and fills my whole screen because it's so large. Error for some reason?

**Comment by nisho5** [comment]
@kimmyzouki , please fix this image from the back office

**Comment by kimmyzouki** [comment]
Will do

**Comment by laurakberglund** [comment]
@kimmyzouki checking in on this, thank you!
