### ISSUE TITLE
Prices missing

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#28]
<img width="1151" alt="screen shot 2016-03-03 at 1 05 59 am" src="https://cloud.githubusercontent.com/assets/16873520/13486107/231d6bb4-e0dc-11e5-9748-ba1cfdce7b3e.png">
<img width="968" alt="screen shot 2016-03-03 at 1 05 54 am" src="https://cloud.githubusercontent.com/assets/16873520/13486108/23293462-e0dc-11e5-8920-07e7c20a52fa.png"> 

prices are missing for all items

**Comment by nisho5** [comment]
There was no prices in the design.
Please advise

**Comment by nisho5** [comment]
There was no prices in the design.
Please advise

**Comment by laurakberglund** [comment]
I've updated the design to include pricing. The packaged Illustrator file can be found here:
https://www.dropbox.com/s/viea023ozpva0zs/Responsive%20Nav%20%26%20other%20edits_Folder.zip?dl=0

I've added the price to the "add to bag" button, like this:

<img width="975" alt="screen shot 2016-03-07 at 12 02 28 am" src="https://cloud.githubusercontent.com/assets/16873520/13561183/f17bd8d8-e3f7-11e5-80a3-3f5fdd8d32d7.png">
<img width="869" alt="screen shot 2016-03-07 at 12 02 40 am" src="https://cloud.githubusercontent.com/assets/16873520/13561184/f184518e-e3f7-11e5-83ee-5ab301b0b26d.png">

**Comment by nisho5** [comment]
Done

**Comment by laurakberglund** [comment]
Language for all buttons like this should be "ORDER NOW FOR $12", not "ADD TO BAG FOR $12".

Also, can we make the grey for the "FOR $12" part of the button slightly darker?
Let's try hex# 818285

<img width="422" alt="screen shot 2016-03-08 at 10 46 14 pm" src="https://cloud.githubusercontent.com/assets/16873520/13624843/b219365c-e57f-11e5-84bb-57d2b460ac8c.png">
<img width="446" alt="screen shot 2016-03-08 at 10 46 40 pm" src="https://cloud.githubusercontent.com/assets/16873520/13624842/b2147798-e57f-11e5-99c0-a851d68c3b2e.png">
