### ISSUE TITLE
Need rollover state on the top nav items

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#29]
When you hover over a nav link, the same green bar should show up like we have on the active state for the nav items.

<img width="226" alt="screen shot 2016-03-03 at 1 13 37 am" src="https://cloud.githubusercontent.com/assets/16873520/13486259/4258ef0c-e0dd-11e5-9b4d-c93d652f2aed.png">

**Comment by nisho5** [comment]
Done

**Comment by laurakberglund** [comment]
The hover state is not showing up for me. Am I looking at the right thing? I'm on beta.goodbytesbox.com, but all these changes you say have been implemented do not look fixed to me.
