### ISSUE TITLE
Nav links from "Order now" page do not work

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#31]
<img width="895" alt="screen shot 2016-03-03 at 1 18 53 am" src="https://cloud.githubusercontent.com/assets/16873520/13486309/e9502f50-e0dd-11e5-81c5-541b7cce8c5f.png">

Also, they are all closer to the top of the browser window than the other set of nav links. They should match the placement of the other set.

**Comment by nisho5** [comment]
Distance fixed.
All links are working except About no? Which is a page im missing. Should it be removed?

**Comment by laurakberglund** [comment]
yes, it can be removed, thanks!

**Comment by laurakberglund** [comment]
Since this "order now" nav is going away/combining with the main nav, I'm going to go ahead and close this issue!
