### ISSUE TITLE
Need consistent messaging on amount you give back

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#32]
I've seen it listed as $1, and I've seen it listed as 10% back, but we need to pick one way to say it, and be consistent throughout the site and all collateral, printed and digital.

<img width="811" alt="screen shot 2016-03-03 at 1 21 15 am" src="https://cloud.githubusercontent.com/assets/16873520/13486352/66cf29c2-e0de-11e5-8a86-267d051c3190.png">
<img width="656" alt="screen shot 2016-03-03 at 1 21 06 am" src="https://cloud.githubusercontent.com/assets/16873520/13486356/68ff0780-e0de-11e5-9a83-78739a12d697.png">

**Comment by laurakberglund** [comment]
@kimmyzouki checking in on this!

**Comment by nisho5** [comment]
Done
