### ISSUE TITLE
Nav overlaps when I resize browser window to tablet size

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#33]
<img width="640" alt="screen shot 2016-03-03 at 1 23 12 am" src="https://cloud.githubusercontent.com/assets/16873520/13486376/8e36c66e-e0de-11e5-8d42-7c5d4e537aae.png">

Nav items are overlapping here - any way to fix? Maybe it jumps to the collapsed nav sooner.

**Comment by nisho5** [comment]
Done for now.
I will fix this collapsing menu and footer issues, once and for all with the equal distance function of the items
