### ISSUE TITLE
Illustrations on homepage start doing weird things at smaller screen sizes

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#34]
The bottom three illustrations get squished on mobile, and then the clock vs. calendar image set jumps to an odd layout on tablet and mobile sizes. We need to retain the view of them side by side with a line dividing them, or they can stack vertically on top of each other.

<img width="402" alt="screen shot 2016-03-03 at 1 24 36 am" src="https://cloud.githubusercontent.com/assets/16873520/13486411/d87fc64e-e0de-11e5-8d69-5e27472dc20d.png">
<img width="965" alt="screen shot 2016-03-03 at 1 25 01 am" src="https://cloud.githubusercontent.com/assets/16873520/13486408/d87b04ce-e0de-11e5-8f87-02abe39a48aa.png">
<img width="424" alt="screen shot 2016-03-03 at 1 24 42 am" src="https://cloud.githubusercontent.com/assets/16873520/13486409/d87b7f26-e0de-11e5-909a-4cebfec889d2.png">
<img width="442" alt="screen shot 2016-03-03 at 1 24 45 am" src="https://cloud.githubusercontent.com/assets/16873520/13486407/d87790aa-e0de-11e5-9dc8-4a406aca120e.png">
<img width="490" alt="screen shot 2016-03-03 at 1 24 51 am" src="https://cloud.githubusercontent.com/assets/16873520/13486410/d87ed432-e0de-11e5-9a35-721f4315b7c3.png">

**Comment by nisho5** [comment]
Done

**Comment by laurakberglund** [comment]
These do not look different to me. I am on Safari

**Comment by laurakberglund** [comment]
After clearing the cache, all the single illustrations look good. But the set with the calendar and the clock is still arranged strangely on mobile.

Instead of this (how it is now) -
<img width="496" alt="screen shot 2016-03-06 at 9 26 41 pm" src="https://cloud.githubusercontent.com/assets/16873520/13559512/e53561ee-e3e2-11e5-9a22-ec0ee09bd517.png">

Can it look like this? -
<img width="496" alt="edit 1" src="https://cloud.githubusercontent.com/assets/16873520/13559517/ecf7af40-e3e2-11e5-9a1a-fe5b06fecc04.png">

**Comment by nisho5** [comment]
Done

**Comment by laurakberglund** [comment]
nice!
