### ISSUE TITLE
Centered middle box in bottom blocks should be a lighter blue, not solid white

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#35]
<img width="615" alt="screen shot 2016-03-03 at 1 27 54 am" src="https://cloud.githubusercontent.com/assets/16873520/13486449/3ae1edf8-e0df-11e5-9c73-9bdbbc4ee646.png">

(for example, on this "How we give back" page - it is white, but it should be a lighter version of the two blocks on either side of it, so it doesn't blend in with the section above it.

**Comment by nisho5** [comment]
Done

**Comment by laurakberglund** [comment]
This looks the same
<img width="853" alt="screen shot 2016-03-06 at 5 29 57 pm" src="https://cloud.githubusercontent.com/assets/16873520/13557573/1c3a7b6a-e3c1-11e5-959b-7019f1a51793.png">

**Comment by laurakberglund** [comment]
Refreshed page / emptied cache - and this box still looks 100% white

**Comment by laurakberglund** [comment]
Hoping to get it to look like this:
<img width="1099" alt="screen shot 2016-03-06 at 9 35 29 pm" src="https://cloud.githubusercontent.com/assets/16873520/13559559/74f01388-e3e3-11e5-82ff-7204fb31c78d.png">

**Comment by nisho5** [comment]
Please check now

**Comment by laurakberglund** [comment]
looks great!
