### ISSUE TITLE
Green color needs to be consistent across design

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#37]
<img width="459" alt="screen shot 2016-03-06 at 10 13 19 pm" src="https://cloud.githubusercontent.com/assets/16873520/13561195/12b3f5d0-e3f8-11e5-88aa-2a5ec94234fc.png">

The green in the nav bar and the green in the headline type are different. The correct green is the color in the nav bar. Please make sure all instances of the green are the hex value 159955.

Hex: 159955

**Comment by nisho5** [comment]
Done
