### ISSUE TITLE
Headline typography

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#39]
The typography in the large headlines needs updating to match the design of the .ai file.

Also, I've added designs for responsive states for the homepage headline type as a reference point for all other pages. (Currently, when the browser window gets smaller, the type remains much too large for the space)

You can download the responsive states for the homepage here (same file as I am linking to in other issues):
https://www.dropbox.com/s/viea023ozpva0zs/Responsive%20Nav%20%26%20other%20edits_Folder.zip?dl=0

Screenshots of examples below:

<img width="892" alt="screen shot 2016-03-07 at 12 53 40 am" src="https://cloud.githubusercontent.com/assets/16873520/13561777/19a77b44-e3ff-11e5-855a-114108c3383c.png">
<img width="731" alt="screen shot 2016-03-07 at 12 54 27 am" src="https://cloud.githubusercontent.com/assets/16873520/13561787/29adf022-e3ff-11e5-9f61-1084e72160f2.png">

<img width="1053" alt="screen shot 2016-03-07 at 12 58 26 am" src="https://cloud.githubusercontent.com/assets/16873520/13561856/c48febcc-e3ff-11e5-944f-9b7878a5cb16.png">
<img width="976" alt="screen shot 2016-03-07 at 1 01 42 am" src="https://cloud.githubusercontent.com/assets/16873520/13561901/305184ec-e400-11e5-8d4c-e7a92c3bc1a5.png">
<img width="1076" alt="screen shot 2016-03-07 at 1 05 08 am" src="https://cloud.githubusercontent.com/assets/16873520/13561937/abb5e02e-e400-11e5-9824-7452a633dee3.png">
<img width="1136" alt="screen shot 2016-03-07 at 1 07 25 am" src="https://cloud.githubusercontent.com/assets/16873520/13561970/fef28df0-e400-11e5-9037-273359eff570.png">
<img width="1165" alt="screen shot 2016-03-07 at 1 10 00 am" src="https://cloud.githubusercontent.com/assets/16873520/13562006/589da7a4-e401-11e5-979d-26cdf3d887fc.png">

**Comment by nisho5** [comment]
I believe we can close this. Menu points already have another issue opened
