### ISSUE TITLE
Top nav text style

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#4]
<img width="416" alt="screen shot 2016-01-25 at 1 09 41 am" src="https://cloud.githubusercontent.com/assets/16873520/12543720/5fb292ec-c300-11e5-9528-12ee8b02568d.png">
<img width="341" alt="screen shot 2016-01-25 at 1 09 28 am" src="https://cloud.githubusercontent.com/assets/16873520/12543721/5fd42dda-c300-11e5-9281-94fdc8ba766e.png">
- Nav text is too close to the top of the browser, needs more breathing room around it
- Needs more letterspacing between all the letters - feels too tight
- Should be semibold type, not bold
- all links need the same amount of space between them

**Comment by nisho5** [comment]
- All done.
  except, just as i mentioned in issue #9 , the alignment if the items is naturally done. If you would like the distance to be exactly the same, I have to remove the centering of each one in its own div, and write a customer code to achieve this. Please let me know.

**Comment by nisho5** [comment]
PS: The font was already Calibre-SemiBold.

**Comment by laurakberglund** [comment]
Thanks for checking on the weight of the font, it must have looked heavy to me because it was so tightly tracked.

<img width="1307" alt="screen shot 2016-01-25 at 10 36 19 pm" src="https://cloud.githubusercontent.com/assets/16873520/12571931/32e48568-c3b4-11e5-9187-2eada4d12d74.png">

The tracking looks much better, but now when the screen gets a little smaller, some of the nav items run to two lines. Is there any way to fix that? Maybe the type needs to get a bit smaller as the screen gets smaller - to 14pts?

**Comment by laurakberglund** [comment]
The nav text is still a bit too close to the top of the browser window as well.

**Comment by laurakberglund** [comment]
I think in order to solve this type running to two lines, we need to create a fixed format for the nav, and then when the screen gets to small to view it at it's fixed width, it will jump to a hamburger nav. I'll work on designing this responsive nav.

For the fixed format for desktop size, can we match this design?:

<img width="1011" alt="screen shot 2016-01-25 at 10 44 22 pm" src="https://cloud.githubusercontent.com/assets/16873520/12572058/47bc754e-c3b5-11e5-87fa-d3d30178dcfe.png">

(And then I'll send you designs for other screen sizes soon)

**Comment by nisho5** [comment]
I think i got this covered. Please check
