### ISSUE TITLE
"Contact" in footer only works from Homepage

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#41]
<img width="225" alt="screen shot 2016-03-07 at 1 21 08 am" src="https://cloud.githubusercontent.com/assets/16873520/13562137/ea1ac3dc-e402-11e5-80af-f9a0a17d808b.png">

On all other pages, it just jumps back to the top of whatever page you are on. (Safari)

**Comment by nisho5** [comment]
Although I could not replicate this, but I added something that should make sure thsi doesn't happen.

Please check.

**Comment by laurakberglund** [comment]
it works!
