### ISSUE TITLE
"Blog" and "Press" should be deactivated for initial launch

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#42]
<img width="965" alt="screen shot 2016-03-07 at 1 22 02 am" src="https://cloud.githubusercontent.com/assets/16873520/13562153/1043989a-e403-11e5-820c-5ba25b3303bd.png">

We do not have pages for these two links to jump to, please deactivate for now.

**Comment by nisho5** [comment]
Done
