### ISSUE TITLE
Bottom box links do not work on any page

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#43]
<img width="1410" alt="screen shot 2016-03-07 at 1 23 36 am" src="https://cloud.githubusercontent.com/assets/16873520/13562168/447e0460-e403-11e5-9e19-d9632d32ff5a.png">

These all need to be activated across the site (same as nav links but as bottom modules)

**Comment by nisho5** [comment]
Done

**Comment by laurakberglund** [comment]
thank you!
