### ISSUE TITLE
Remove any ingredients that do not currently have a photo

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#44]
We won't have images for these ingredients for launch, so we should remove the instances of ingredients that are missing a photo.

We should add into the description the missing ingredients, so people still know what is in each box for launch. (Kimmy) 

(We will revisit this again in late March, when we have images of all the new ingredients and dressings / sauces)

<img width="227" alt="screen shot 2016-03-07 at 1 25 17 am" src="https://cloud.githubusercontent.com/assets/16873520/13562196/a260d602-e403-11e5-9fd3-fad362cc31e9.png">

**Comment by nisho5** [comment]
@kimmyzouki  please check

**Comment by laurakberglund** [comment]
@kimmyzouki checking in on this!

**Comment by kimmyzouki** [comment]
this should be closed!
All ingredients are with the right pics or am i missing something?

**Comment by laurakberglund** [comment]
@kimmyzouki the "sprouts" are still showing up as a question mark, thanks!

**Comment by nisho5** [comment]
Can we close this ?
