### ISSUE TITLE
Once a user logs in, they should be directed straight to the "order now" page

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#45]
The homepage with all the nav items on that page are only useful to get new users to sign up. Once they are in our system, it should jump them to the actual product, the ordering page.

(Once they see this modal, or the modal that says you are in the zone and ready to order, it should redirect to the "order now" page):
<img width="602" alt="screen shot 2016-03-07 at 1 43 55 am" src="https://cloud.githubusercontent.com/assets/16873520/13562524/b991628e-e407-11e5-91d2-e8ef3764c1c1.png">

**Comment by nisho5** [comment]
Done

**Comment by laurakberglund** [comment]
thank you!
