### ISSUE TITLE
Team photos need to be updated before launch

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#47]
Kimmy- please send me the images you would like to use here and I will reformat for web. 

<img width="1144" alt="screen shot 2016-03-07 at 1 59 16 am" src="https://cloud.githubusercontent.com/assets/16873520/13562585/488f5054-e408-11e5-8866-dfe02f197b7b.png">
<img width="1216" alt="screen shot 2016-03-07 at 1 59 11 am" src="https://cloud.githubusercontent.com/assets/16873520/13562586/48a026e0-e408-11e5-9b25-222ce33a3578.png">

**Comment by kimmyzouki** [comment]
on it

**Comment by laurakberglund** [comment]
@kimmyzouki I received some images from Dan for your photo, but have we gotten anything from Sebastien's wife for Sebastien's photo? Let me know, thanks!

**Comment by laurakberglund** [comment]
Here is Kimmy's picture, which will be the second one on the page. @nisho5 
![kimmy-picture](https://cloud.githubusercontent.com/assets/16873520/13624581/8dcb5ce6-e57d-11e5-9f8c-757b65c1f49c.jpg)

**Comment by nisho5** [comment]
Replaced

**Comment by nisho5** [comment]
Waiting for first picture

**Comment by kimmyzouki** [comment]
by the way i am changing my photo big time!
jesus.. no way this is getting published :)))

**Comment by laurakberglund** [comment]
haha

**Comment by laurakberglund** [comment]
New photos to be uploaded @nisho5 :
![kimmy-final](https://cloud.githubusercontent.com/assets/16873520/13725906/eb802ffc-e87e-11e5-87ea-d9c1752b21ec.jpg)
![sebastien-final](https://cloud.githubusercontent.com/assets/16873520/13725905/eb7f8a84-e87e-11e5-8cb8-f3396d1a2e1a.jpg)
