### ISSUE TITLE
Ingredient labeled wrong under kale caesar box

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#48]
http://beta.goodbytesbox.com/individualorders.html

<img width="242" alt="screen shot 2016-03-07 at 2 03 04 am" src="https://cloud.githubusercontent.com/assets/16873520/13562667/d10a2698-e408-11e5-9dc6-30e163b8b2f2.png">

We don't have a photo of the white bean dressing yet, so please remove this ingredient for now. It should just be mentioned in the description until we can provide a new image.

**Comment by nisho5** [comment]
@kimmyzouki  Please remove this

**Comment by laurakberglund** [comment]
@kimmyzouki checking in on this, thank you!

**Comment by kimmyzouki** [comment]
should be sorted
