### ISSUE TITLE
Logo in green nav band needs to shrink

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#5]
<img width="221" alt="screen shot 2016-01-25 at 1 12 19 am" src="https://cloud.githubusercontent.com/assets/16873520/12543749/bf294fea-c300-11e5-9820-45a535d6c2a9.png">
<img width="216" alt="screen shot 2016-01-25 at 1 12 11 am" src="https://cloud.githubusercontent.com/assets/16873520/12543750/bf3d4324-c300-11e5-9ee0-3d5fe97393a8.png">

When the top nav switches to the green band, the logo needs to animate to a smaller scale, to fit more comfortably within the green strip.

Also, this white version looks blurry on my screen, needs to look as crisp as all the type

**Comment by nisho5** [comment]
- Done

**Comment by laurakberglund** [comment]
This is not shrinking for me

**Comment by nisho5** [comment]
Do u mean when u scroll and the White on Green logo, is the same size as the original? Please double check from the new URL i'll be sending to you once i'm done tonight

**Comment by laurakberglund** [comment]
I'm actually looking for a little bit of an animation when it switches to the green bar: I'd like the white logo to shrink down within it, so it takes up less room within the green bar.

Similar to this tutorial (watch how the logo shrinks in the top left as you scroll down). 
http://callmenick.com/_development/resize-header-on-scroll/

Is this possible?

**Comment by laurakberglund** [comment]
<img width="486" alt="screen shot 2016-03-03 at 12 28 37 am" src="https://cloud.githubusercontent.com/assets/16873520/13485987/0f809c76-e0db-11e5-9f83-f5a45feb33bd.png">

I just saw the logo blow up to the old bigger size again on the homepage after I clicked a few links, hopefully we can get that fixed!
