### ISSUE TITLE
"Account" link in nav does not work, jumps me to homepage

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#50]
Even when I am logged in with my account (I am not in the good bytes zone though), when I click "account" it jumps me to the homepage, not to an account page. I cannot see the account page at all right now.

**Comment by nisho5** [comment]
I checked, and it is not the case with me.
Could you please give me access to your account so that I test online.
Thank you

**Comment by laurakberglund** [comment]
how strange, it's working for me now! (I started fresh with a another new account, and it works)

**Comment by laurakberglund** [comment]
Ok, it's now doing it again with this new account I've made. It also jumps me to the homepage when I click "bag" in the top nav as well.

You can login with this info:
email: lauraberglundtesting@gmail.com
pass: testing123
