### ISSUE TITLE
Modal animations / black hairline around them

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#51]
When a modal pops up now (like the sign in or register modal), it quickly slides in from the top. Can we simplify this so it just pops up on the screen where it's supposed to? The animation feels like too much.

Also, for some reason a blue line is showing up around the edges of all the modals. We need to make sure that those lines do not show up.

Example of the blue line:
<img width="603" alt="screen shot 2016-03-03 at 12 42 33 am" src="https://cloud.githubusercontent.com/assets/16873520/13574747/7a239ee0-e453-11e5-9dc0-2395cf017130.png">

**Comment by nisho5** [comment]
Done

**Comment by laurakberglund** [comment]
It looks the the blue line issue may have resolved itself, but now I'm noticing a hairline black border around these modals that needs to be removed. 

Also, the points of these modals are slightly rounded, is it possible to make them come to a true point?

**Comment by laurakberglund** [comment]
Also, from what I can tell, the only modal that is still animating in from the top is the "Contact us" modal. Please remove the animation from this modal.

**Comment by laurakberglund** [comment]
image of the black hairline stroke I was talking about (and the rounded corner) <img width="283" alt="screen shot 2016-03-08 at 9 33 20 pm" src="https://cloud.githubusercontent.com/assets/16873520/13624721/9201ecde-e57e-11e5-803b-91d0df0fbbd8.png">

**Comment by nisho5** [comment]
Done
