### ISSUE TITLE
force line break to resolve widow

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#53]
<img width="794" alt="screen shot 2016-03-08 at 11 35 33 pm" src="https://cloud.githubusercontent.com/assets/16873520/13625516/8a46b21a-e586-11e5-9623-1931a1fbdb93.png">

In some browser sizes, the word "good" hangs by itself. Can we make sure that this headline is either all one line, or when the browser gets too small to fit, we force a line break between "meals" and "with"?

like this:
<img width="608" alt="screen shot 2016-03-08 at 11 37 32 pm" src="https://cloud.githubusercontent.com/assets/16873520/13625542/c463cf14-e586-11e5-958a-65d59f5cf177.png">

**Comment by nisho5** [comment]
done
