### ISSUE TITLE
Homepage > bottom module

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#54]
on this site it says: "Sounds good?" / "Get started":
<img width="376" alt="screen shot 2016-03-08 at 11 40 13 pm" src="https://cloud.githubusercontent.com/assets/16873520/13625591/454e5c16-e587-11e5-8a4b-159568ba42a7.png">

But it should say this: "Sound good?" (no 's' in 'sound') / "Order now":
<img width="333" alt="screen shot 2016-03-08 at 11 40 03 pm" src="https://cloud.githubusercontent.com/assets/16873520/13625595/4f6df94a-e587-11e5-8dc1-4ca7856a95db.png">

**Comment by nisho5** [comment]
Fixed.
But now, does the ORDER NOW button take you to order now page? or still open the sign up form?

**Comment by laurakberglund** [comment]
If a user is already signed in, then it would take you to the "order now" page. If a user is not signed in, then it would open the sign up form.

**Comment by laurakberglund** [comment]
Please keep noting in these issues if you have addressed them or not. I want to start clearing some of these out, but I don't know which ones you have seen yet @nisho5 , thanks!

**Comment by nisho5** [comment]
I believe we can close this one too
