### ISSUE TITLE
Button sizes

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#55]
Overall, the buttons are too big throughout the site. 
If the small headlines are 16px, then the type inside the buttons should be smaller (12px).
Then the boxes of the buttons should also get smaller.
See screenshots for reference (applies to all boxed buttons on the site):

<img width="575" alt="screen shot 2016-03-09 at 12 00 10 am" src="https://cloud.githubusercontent.com/assets/16873520/13625855/0d0e830a-e58a-11e5-825b-4404abe84ce4.png">
<img width="417" alt="screen shot 2016-03-09 at 12 01 59 am" src="https://cloud.githubusercontent.com/assets/16873520/13625871/3991c770-e58a-11e5-84a1-5eb8279ee546.png">

**Comment by nisho5** [comment]
Done
