### ISSUE TITLE
In-line link color should be the brand green

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#6]
<img width="195" alt="screen shot 2016-01-25 at 1 14 29 am" src="https://cloud.githubusercontent.com/assets/16873520/12543803/425f42ca-c301-11e5-8b63-2a2f6cee95a3.png">

<img width="73" alt="screen shot 2016-01-25 at 1 16 52 am" src="https://cloud.githubusercontent.com/assets/16873520/12543807/55686004-c301-11e5-91fd-4bc56f2ed415.png">

On homepage:

Any links on the site in-line with the text should never be blue - they should be the brand green color, unless otherwise noted

**Comment by nisho5** [comment]
- Done

**Comment by laurakberglund** [comment]
looks good!
