### ISSUE TITLE
"Sign in" link at bottom of homepage disappears on hover

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#62]
This is what it looks like on hover:

<img width="252" alt="screen shot 2016-03-12 at 9 10 17 pm" src="https://cloud.githubusercontent.com/assets/16873520/13726491/52e4be02-e897-11e5-82bf-0afc7c6c73b4.png">

Can we make the hover state white instead?

**Comment by nisho5** [comment]
Done
