### ISSUE TITLE
Nav design

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#68]
Hi Neshan - not sure if you are still working through updates on this or not, but I'm just noticing that what you have implemented is not completely reflecting the Illustrator file I gave you. 

A few points:
- address on far right: when it is on green, the checkmark icon should appear black.
- whenever it appears as an address there, it should function as a link to the "account" page.
- the type for "order now", "group orders", giving back", and "the team" should be size 12px, and the letters should appear more spaced out than you have it.
- the type for the text on the far right ("sign in / register", [address]) should be size 10px, and the letters should be more spaced out than you have it.
- the nav items (order now, group orders, giving back, the team, [social icons]) should be centered on the page, right now they look too far to the left.
- when it says "sign in / register" on the far right, the "/" should never turn green on hover, it should always stay black (or white when it is on the green band)
- the good bytes logo should also have a rollover state. When it is not in the green band, it's normal state should be black, and it's hover state should be green. When it's on the green band, it's normal state should be white (like everything else), and then turn black on hover (like everything else)
- the social icons: when they are on the regular background color, their normal state should be black, and their hover state should be green. When they are on the green color, then their normal state should be white, and their hover state should be black.
- the line underneath the nav items is not the active state. That line should always be used permanently under the "order now" nav item, to make it look more important. It should also change color on hover to match the same hover state as the type.

**Comment by nisho5** [comment]
Hey Laura,

Yup, I still haven't finished it.
But thanks for the points, this'll make it easy for me.
