### ISSUE TITLE
Subheds and body text feels tight

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#7]
<img width="876" alt="screen shot 2016-01-25 at 1 18 13 am" src="https://cloud.githubusercontent.com/assets/16873520/12543838/9b03dcba-c301-11e5-9512-5f0b2baad7e8.png">
<img width="837" alt="screen shot 2016-01-25 at 1 18 01 am" src="https://cloud.githubusercontent.com/assets/16873520/12543837/9b0228fc-c301-11e5-9612-6fe56231be99.png">

On homepage:
- Increase letterspacing in subhed text
- Decrease size of subhed text by a point or two (feels a bit too big)
- Increase leading (space between each line of text) in the body text so it's not as close together
- Green callout should be "do good", not just "good"

**Comment by nisho5** [comment]
Done

**Comment by nisho5** [comment]
Please check

**Comment by laurakberglund** [comment]
beautiful
