### ISSUE TITLE
Line under "order now" in nav is too long

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#70]
It should be the exact same width as the type.

What we have now:
<img width="124" alt="screen shot 2016-03-17 at 10 47 18 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867135/8b286e40-ec92-11e5-9fbb-14102e19e795.png">
<img width="133" alt="screen shot 2016-03-17 at 10 49 58 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867144/98069a1a-ec92-11e5-801d-090df4a67f5a.png">

What it should look like:
<img width="350" alt="screen shot 2016-03-17 at 10 49 07 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867138/91297f28-ec92-11e5-9665-1f00ca3634d5.png">
<img width="346" alt="screen shot 2016-03-17 at 10 50 18 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867147/a409ee02-ec92-11e5-9702-281c60d1e2ba.png">

**Comment by nisho5** [comment]
Done
