### ISSUE TITLE
Headline type got moved up, it should appear optically centered

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#72]
The big headline type on the homepage is higher up than it used to be - we need to lower it back down so it appears vertically centered within the yellow background area.

What we have now:
<img width="1355" alt="screen shot 2016-03-17 at 10 53 05 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867203/2ea9d162-ec93-11e5-9888-18eaa53b6b54.png">

What it should look like:
<img width="801" alt="screen shot 2016-03-17 at 10 52 54 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867205/3647343c-ec93-11e5-98f7-abd5225be0c9.png">

**Comment by laurakberglund** [comment]
Also can we reduce the leading on the headlines slightly? (for ALL of this style of headline throughout the site.) The spacing between the lines is too big, compared to the original design.

See the difference in tracking for the group orders page, as another example:
<img width="733" alt="screen shot 2016-03-17 at 11 02 54 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867357/96439b22-ec94-11e5-9a63-3e0c790bcbcb.png">
<img width="555" alt="screen shot 2016-03-17 at 11 03 43 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867358/9648bb34-ec94-11e5-93ae-6c5623a28780.png">

**Comment by nisho5** [comment]
Done, please check
