### ISSUE TITLE
Spacing missing between boxes on group orders page

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#74]
What we have now:
<img width="227" alt="screen shot 2016-03-17 at 11 04 57 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867389/deb315c2-ec94-11e5-941a-91fcde99c32b.png">

What we should have:
<img width="500" alt="screen shot 2016-03-17 at 11 06 06 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867391/e3df99da-ec94-11e5-83df-2ebb3d6e4f37.png">

We are missing the margin of space between the boxes side by side on the group orders page. Can we add 22 px as a margin between them all?

Also, the vertical spacing is off as well:

What we have:
<img width="584" alt="screen shot 2016-03-17 at 11 09 03 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867440/4919c0b4-ec95-11e5-8e97-1f3259fb7cf3.png">

What we should have:
<img width="545" alt="screen shot 2016-03-17 at 11 09 42 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867453/5a48a364-ec95-11e5-9dc5-b783e503a373.png">

(There should be 54px of space between the bottom of the "gluten-free, vegetarian, nut-free" type and the top of the photo below it (on all boxes on this page).

**Comment by nisho5** [comment]
Please check
