### ISSUE TITLE
Need active state in top nav

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#76]
When you click to a new page, there is no indication in the nav now that you successfully clicked to that page. Can we make the active state the same color as we are using for all the hover state colors?

On this page, the "Group Orders" should appear green:
<img width="821" alt="screen shot 2016-03-17 at 11 17 00 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867581/c0beae80-ec96-11e5-91b7-fb23c85f50ca.png">

And should appear black when it is within the green band:
<img width="741" alt="screen shot 2016-03-17 at 11 17 04 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867582/c0c74b62-ec96-11e5-9356-d922ba51f0d0.png">

**Comment by nisho5** [comment]
Done, please check
