### ISSUE TITLE
Fix rag on this paragraph (giving back page)

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#77]
<img width="857" alt="screen shot 2016-03-17 at 11 16 41 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867595/fbc32222-ec96-11e5-8dfa-3a410d3106d8.png">

The second-to-last line is so much longer than the others, can we make sure there are no forced line breaks in this paragraph?

Also, can we add a dash and a space right before Christine Byrd's name, so it looks more like a credit?

So-
Instead of this: "Christine Byrd" on a line by itself
It should say this: "- Christine Byrd" on a line by itself.

**Comment by laurakberglund** [comment]
Just tested this paragraph out on a smaller screen size - there are definitely some forced line breaks going on here. We need to remove those, to avoid it looking like this:

<img width="534" alt="screen shot 2016-03-17 at 11 24 07 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867632/70e500e8-ec97-11e5-8c53-2e68f3c4ad6e.png">

**Comment by nisho5** [comment]
Fixed
