### ISSUE TITLE
type under icons on giving back page

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#78]
what we have now:
<img width="971" alt="screen shot 2016-03-17 at 11 24 59 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867656/87563590-ec97-11e5-9258-cf1cc9977438.png">

What the type should look like:
<img width="850" alt="screen shot 2016-03-17 at 11 25 40 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867664/9992cf66-ec97-11e5-9864-2b941c9ff882.png">

We need to increase the tracking on these three pieces of type, so they match the "A partnership for innovation" headline type exactly (which can be found further down that page)

**Comment by nisho5** [comment]
Done, please check
