### ISSUE TITLE
"place your order by..." type on Order Now page

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#79]
The "place your order by..." type on this page is a bit too big, heavy, and needs to be more tracked out:

What we have:
<img width="582" alt="screen shot 2016-03-17 at 11 32 48 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867743/97fb195a-ec98-11e5-9b9a-beb6aa574fdf.png">

What we should have:
<img width="570" alt="screen shot 2016-03-17 at 11 35 58 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867792/074c6228-ec99-11e5-8145-8854d94ad707.png">

The type here needs to be 16px, and it should be more tracked out (to match all the other smaller all-caps headlines we have though out the site)

Also, since this is supposed to appear more secondary than the other headlines, we need to make it a slightly lighter weight than it is now. (So if it's semi-bold, take it to regular, etc)

**Comment by nisho5** [comment]
Done, please check
