### ISSUE TITLE
DonorsChoose block on homepage

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#8]
<img width="602" alt="screen shot 2016-01-25 at 1 21 54 am" src="https://cloud.githubusercontent.com/assets/16873520/12543885/273bff78-c302-11e5-9275-ad73fc0e1d27.png">
<img width="640" alt="screen shot 2016-01-25 at 1 22 06 am" src="https://cloud.githubusercontent.com/assets/16873520/12543886/2753b532-c302-11e5-8172-afebfc5c4e47.png">
- size of logo needs to get slightly smaller
- everthing in this block needs to get more spaced out vertically (needs more breathing room around the logo)
- logo looks blurry, need to use 2x sizes
- Same comments for the text styles in the subhed and body text as before
- Same comments for the button style as before
- Same comment for the in-line link color as before

**Comment by nisho5** [comment]
Done

**Comment by laurakberglund** [comment]
Looks good
