### ISSUE TITLE
Meal attributes should be slightly less tracked out

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#80]
This is for the "order now" page and the "Group orders" page:

What we have now:
<img width="286" alt="screen shot 2016-03-17 at 11 37 27 pm" src="https://cloud.githubusercontent.com/assets/16873520/13867837/5f2568f0-ec99-11e5-8570-f383c379a224.png">

Can we make this type for all meal attributes in this style just a tiny bit less tracked out? (should be the same tracking for all the smaller all-caps headlines on the site)

**Comment by nisho5** [comment]
Done, please check
