### ISSUE TITLE
Change wording from "Incorrect login credentials"

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#84]
<img width="396" alt="screen shot 2016-03-17 at 11 58 54 pm" src="https://cloud.githubusercontent.com/assets/16873520/13868129/4033fa76-ec9c-11e5-974c-a9ef1bf760e6.png">

This wording needs to change from "Incorrect login credentials" to "Username or password is incorrect"

**Comment by nisho5** [comment]
Done, please check
