### ISSUE TITLE
"Welcome" type is too far left compared to rest of type

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#86]
<img width="566" alt="screen shot 2016-03-18 at 12 02 58 am" src="https://cloud.githubusercontent.com/assets/16873520/13868300/8c2cc1b4-ec9d-11e5-93d3-86c0230063fa.png">

On this modal, the "welcome" in "Welcome, friend!" looks like it got bumped slightly to the left. Can we make sure that it is centered with the "Friend!" type below it?

**Comment by nisho5** [comment]
Done, please check
