### ISSUE TITLE
Ingredient images need to be scaled to 50% each

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#88]
I saved them all out at 2x size, but they should not appear twice as big on the site (it's just so they are retina-friendly). Can we reduce the scale of all the ingredient images to 50% of what they are now?

What we have now:
<img width="987" alt="screen shot 2016-03-18 at 12 19 09 am" src="https://cloud.githubusercontent.com/assets/16873520/13868450/3ef49f78-ec9f-11e5-8b63-58c6f78cc4d1.png">

The size they should be (each one should technically fit within the white circles):
<img width="1014" alt="screen shot 2016-03-18 at 12 19 23 am" src="https://cloud.githubusercontent.com/assets/16873520/13868454/506ee4d4-ec9f-11e5-96e2-5054e0875716.png">

**Comment by nisho5** [comment]
Done, please check

**Comment by laurakberglund** [comment]
Only some of the modals have smaller ingredients. Please see:

<img width="908" alt="screen shot 2016-03-20 at 5 32 47 pm" src="https://cloud.githubusercontent.com/assets/16873520/13907317/d5d9aea0-eec1-11e5-8cf7-dd6573b9d925.png">
<img width="971" alt="screen shot 2016-03-20 at 5 32 54 pm" src="https://cloud.githubusercontent.com/assets/16873520/13907318/d5daff4e-eec1-11e5-845a-2beff9a7c8f9.png">

They all need to be the same smaller size.

**Comment by nisho5** [comment]
Yeah, coz I'd put percentage before, now that some meals have 3 ingredients per row, the percentage differed. Now I set it to a fixed width in pixels
