### ISSUE TITLE
Way we organize ingredients

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#89]
I want to try to avoid having a single ingredient floating by itself on a row whenever possible. 

Can we do something where instead of having two rows of 4 and then a third row of just one, we do three rows of 3? (I don't want to always be three columns though, especially when we have 8 ingredients to show, then they should be shown in two rows of 4). Is it possible to have it appear differently for different numbers of ingredients?

Instead of this for ones with 9 ingredients:
<img width="940" alt="screen shot 2016-03-18 at 12 21 56 am" src="https://cloud.githubusercontent.com/assets/16873520/13868498/d7c9d8e4-ec9f-11e5-99e5-b558625dd3ef.png">

Can we shift it to this for 9 ingredient boxes?:
<img width="940" alt="edit" src="https://cloud.githubusercontent.com/assets/16873520/13868532/4defe9c8-eca0-11e5-9023-71f823c5be13.png">

**Comment by nisho5** [comment]
Done, please check
