### ISSUE TITLE
Footer styling

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#9]
<img width="525" alt="screen shot 2016-01-25 at 1 25 20 am" src="https://cloud.githubusercontent.com/assets/16873520/12543925/99cea450-c302-11e5-8adf-6db41951e39d.png">
<img width="831" alt="screen shot 2016-01-25 at 1 25 27 am" src="https://cloud.githubusercontent.com/assets/16873520/12543924/99ccc5e0-c302-11e5-9afc-e5898bdb1122.png">
- black box for the footer should be taller
- Text in footer should have more letterspacing between letters
- make sure footer info is centered within the browser window (right now it's more to the left)
- links needs the same amount of space between them all

**Comment by nisho5** [comment]
- First three points complete
- Last Point: words spacing: by default this is the default behavior of equally aligned list items. If you insist, I'll have to write some code to calculate distances and add distance manually based on the largest word. Let me know what do you suggest.

**Comment by laurakberglund** [comment]
I think this looks great now, except that "Privacy Policy" is running onto two lines. If the only way to fix that and keep the same spacing between the links is to add the extra code, is that possible to do? This may be beneficial for the top nav as well. Let me know!

**Comment by nisho5** [comment]
Fixed the two line thing in the footer also.
Please open a new issue for the "words spacing" thing that i need to do manually.
I'll do that once i finish the basic stuff.
Thanks

**Comment by laurakberglund** [comment]
Great, thanks!
