### ISSUE TITLE
Won't let me add to bag even though I am in the zone

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#90]
<img width="1134" alt="screen shot 2016-03-18 at 12 28 45 am" src="https://cloud.githubusercontent.com/assets/16873520/13868541/6f1df9e6-eca0-11e5-840f-1791c47ae07c.png">

I just tried adding a box to my bag, but when I attempted it, it jumped be back to the homepage with the modal to sign in popped up.

(You can see in the top right corner that I am supposed to be signed in, and within the delivery zone already.)

**Comment by laurakberglund** [comment]
Just happened again with another new test email I created for this.

If you'd like to investigate:

email: lauraberglundtesting2@gmail.com
pass: testing

or 

email: lauraberglundtesting@gmail.com
pass: testing

It happened on both of these accounts.

Also, because I'm unable to add anything to my bag, I can't QA things like the ordering process, items in my bag, the confirmation email, etc. We'll need to make sure this is functioning smoothly before we do anything else.

@kimmyzouki @nisho5

**Comment by nisho5** [comment]
These all are the same problem, somehow your browser is blocking something, and/or my code is not able to mark ur login state. Please go to issue #92 I have left a comment there to test.
