### ISSUE TITLE
address in top right nav

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#91]
- only the address type should act as a link to the account page, not the checkmark or "x" icon. The icon part should just be a static asset (should not turn colors when you hover over it ever).
- when the address is on the standard background color, the icon (checkmark or "x") should appear static and green, while the type is black. 

what we have:
<img width="327" alt="screen shot 2016-03-18 at 12 30 40 am" src="https://cloud.githubusercontent.com/assets/16873520/13868601/270a4a6e-eca1-11e5-82ce-7b6ebb193ce8.png">

What we should have:
<img width="313" alt="screen shot 2016-03-18 at 12 34 40 am" src="https://cloud.githubusercontent.com/assets/16873520/13868610/38f6b618-eca1-11e5-8029-a23ce2a0cd04.png">
- when the address is on the green band, the icon (checkmark or "x") should appear static and black, while the type is white.

what we have:
<img width="281" alt="screen shot 2016-03-18 at 12 30 44 am" src="https://cloud.githubusercontent.com/assets/16873520/13868613/3f111a5c-eca1-11e5-8232-f82351c276b1.png">

what we should have:
<img width="317" alt="screen shot 2016-03-18 at 12 35 11 am" src="https://cloud.githubusercontent.com/assets/16873520/13868616/4a2780ac-eca1-11e5-92e4-2fc9f361ff7f.png">

**Comment by nisho5** [comment]
Done, please check
