### ISSUE TITLE
address link in nav does not take me to "account" page

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#92]
When I click my address in the nav, it keeps me on the homepage, and makes the "sign in" modal pop up, like I am not signed in.
<img width="992" alt="screen shot 2016-03-18 at 12 36 12 am" src="https://cloud.githubusercontent.com/assets/16873520/13868661/9574b412-eca1-11e5-97f9-6a08170fa691.png">

**Comment by nisho5** [comment]
Laura, do u have cookies disabled by any chance?
Although I doubt it, but could you please try to go to this site, it will tell you if so

http://www.whatarecookies.com/cookietest.asp

**Comment by laurakberglund** [comment]
They are enabled!

<img width="413" alt="screen shot 2016-03-20 at 7 43 03 pm" src="https://cloud.githubusercontent.com/assets/16873520/13908179/017fff52-eed4-11e5-9d8d-2aa7625b0b79.png">

**Comment by nisho5** [comment]
Could you please try a different browser? Although Kimmy is on Mac and Safari too, but he is not facing any issues, but let's try it.

Or if you could try a different computer.

First thing, I want to narrow down how generic is this bug or if it's specific.
