### ISSUE TITLE
"Delivery" section breaks on Account page

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#93]
When I clicked "edit" in the delivery section on the account page, it showed an arrow on the left side and "save" on the right, but neither button or dropdown was functional.

<img width="582" alt="screen shot 2016-03-20 at 4 45 10 pm" src="https://cloud.githubusercontent.com/assets/16873520/13907029/4646b608-eebb-11e5-847d-14cf519404c2.png">

**Comment by nisho5** [comment]
Fixed
