### ISSUE TITLE
Adding a box to my bag

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#94]
When I add a box to my bag, it doesn't immediately register in the nav. (The address with the check mark stays visible, and does not automatically change to the bag icon with the red "1" next to it.)

I had to click around to a new page, before the icon refreshed to the bag.

We need to make sure that the switch happens immediately as they click the "add to bag" button. They should _see_ it happen on the page.

**Comment by nisho5** [comment]
Done
