### ISSUE TITLE
Increase padding between name of ingredient and photo of ingredient

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#97]
<img width="213" alt="screen shot 2016-03-20 at 6 47 32 pm" src="https://cloud.githubusercontent.com/assets/16873520/13907769/4ac10f88-eecc-11e5-87a8-79de149f433e.png">

Please update on all to have more padding.

Should look like this (20px of space):
<img width="801" alt="screen shot 2016-03-20 at 6 52 02 pm" src="https://cloud.githubusercontent.com/assets/16873520/13907799/da3fbea2-eecc-11e5-9213-982ae7bd9f5f.png">

**Comment by nisho5** [comment]
Done
