### ISSUE TITLE
Two photos on homepage not showing up on mobile

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#98]
![img_9728](https://cloud.githubusercontent.com/assets/16873520/13993394/98bf416a-f0f6-11e5-96d4-140011cb52d6.PNG)
![img_9729](https://cloud.githubusercontent.com/assets/16873520/13993395/98f95dc8-f0f6-11e5-8c8b-88cdfbf1ee9b.PNG)
- The 10 lunch box image
- The Group orders illustration
  @nisho5

**Comment by nisho5** [comment]
This should be ok now.
